version: '3.3'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: yparkw
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qkr102998!!

  client:
      build: 
        context: ./client
        dockerfile: Dockerfile
      restart: always
      depends_on:
        - server

  server:
    build: ./server
    restart: always
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./server:/app
      - ./server/logs:/app/logs
      - ./client/build:/usr/share/nginx/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    expose:
      - "8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./client/build:/usr/share/nginx/html
      - /etc/letsencrypt/live/yparkw.com/fullchain.pem:/etc/letsencrypt/live/yparkw.com/fullchain.pem
      - /etc/letsencrypt/live/www.yparkw.com/privkey.pem:/etc/letsencrypt/live/www.yparkw.com/privkey.pem
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./client/build:/usr/share/nginx/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/certbot --email ehgus.dev.8621@gmail.com --agree-tos --no-eff-email --force-renewal -d yparkw.com -d www.yparkw.com

  