version: '3.3'

services:
  client:
      build: 
        context: ./client
        dockerfile: Dockerfile
      restart: always
      ports:
        - "80:80"
      depends_on:
        - server

  server:
    build: ./server
    restart: always
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./server:/app
      - ./server/logs:/app/logs
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod

  