version: '3.3'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: yparkw
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qkr102998!!

  client:
      build: 
        context: ./client
        dockerfile: Dockerfile
      restart: always
      depends_on:
        - server

  server:
    build: ./server
    restart: always
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./server:/app
      - ./server/logs:/app/logs
      - ./client/build:/usr/share/nginx/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    expose:
      - "8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
