version: '3.3'

services:
  server:
    build: ./server
    restart: always
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./server:/server
      - ./server/logs:/server/logs
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod

  client:
    build: ./client
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client

  nginx:
    build: ./nginx
    restart: always
    image: nginx:1.18.0
    volumes:
      - ./server/static:/server/static
      - ./server/media:/server/media
    ports:
      - "80:80"
    depends_on:
      - server
      - client

